name: Meu primeiro workflow

on:
  workflow_dispatch:

jobs:
  aprender-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Listar arquivos
        run: ls -la

      - name: Mostrar mensagem
        run: echo "Olá, GitHub Actions!"
